server:
  port: 8081
spring:
  application:
    name: order
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/bunny?characterEncoding=utf-8&userSSL=false
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password:
  jpa:
    show-sql: true
  rabbitmq:
    host: 192.168.99.100
    port: 5672
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
env: test666
